spring.application.name=Gest2


server.servlet.context-path=/SpringMVC

spring.mvc.servlet.path=/servlet

server.port=8081


DATABASE ###

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/agence2

spring.datasource.username=root

spring.datasource.password=




spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update



spring.mvc.view.prefix=/views/

spring.mvc.view.suffix=.jsp